services:
  byparr:
    image: ghcr.io/thephaseless/byparr
    container_name: byparr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
    labels:
      - traefik.enable=true
      - traefik.http.routers.byparr.rule=Host(`${BYPARR_HOSTNAME?}`)
      - traefik.http.routers.byparr.entrypoints=websecure
      - traefik.http.routers.byparr.tls.certresolver=letsencrypt
      - traefik.http.routers.byparr.middlewares=authelia@docker
    volumes:
      - ${DOCKER_DATA_DIR}/byparr/screenshots:/app/screenshots 
    healthcheck:
      test: curl -f http://localhost:8191/health
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 10s
    profiles:
      - byparr
      - stremio
      - debrid_media_server
      - all
